"""add initial data

Revision ID: 380e97e790f2
Revises: 4731879918a7
Create Date: 2026-01-31 16:31:54.094671

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import solar_panel.internal.db


# revision identifiers, used by Alembic.
revision: str = "380e97e790f2"
down_revision: Union[str, None] = "4731879918a7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    device_table = sa.table(
        "devices",
        sa.column("id", sa.INTEGER()),
        sa.column("name", sa.TEXT()),
        sa.column("description", sa.TEXT()),
        sa.column("created_at", sa.BIGINT()),
    )

    op.bulk_insert(
        device_table,
        [  # DDSU Meters (IDs 2, 4-8)
            {
                "id": "2",
                "name": "Grid Meter",
                "description": "Main Utility Grid Connection (DDSU666)",
            },
            {
                "id": "4",
                "name": "Server Rack 1",
                "description": "Power monitoring for Server Cluster 1",
            },
            {
                "id": "5",
                "name": "Server Rack 2",
                "description": "Power monitoring for Server Cluster 2",
            },
            {
                "id": "6",
                "name": "Server Rack 3",
                "description": "Power monitoring for Server Cluster 3",
            },
            {
                "id": "7",
                "name": "Server Rack 4",
                "description": "Power monitoring for Server Cluster 4",
            },
            {
                "id": "8",
                "name": "Server Rack 5",
                "description": "Power monitoring for Server Cluster 5",
            },
            # PZEM Meter (ID 3)
            {
                "id": "3",
                "name": "PV Generation",
                "description": "Solar Panel DC/AC Generation Output",
            },
            # SHT Sensor (ID 1)
            {
                "id": "1",
                "name": "Server Room SHT",
                "description": "Ambient Temperature and Humidity Sensor",
            },
        ],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "DELETE FROM device_records WHERE id IN ('1', '2', '3', '4', '5', '6', '7', '8')"
    )
    # ### end Alembic commands ###
