"""init

Revision ID: 4731879918a7
Revises:
Create Date: 2026-01-28 21:24:34.215130

"""

import time
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import solar_panel.internal.db
from solar_panel.migrations.util import get_existing_tables


# revision identifiers, used by Alembic.
revision: str = "4731879918a7"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    existing_tables = set(get_existing_tables())

    # ### commands auto generated by Alembic - please adjust! ###
    if "devices" not in existing_tables:
        op.create_table(
            "devices",
            sa.Column("id", sa.INTEGER(), nullable=False),
            sa.Column("name", sa.TEXT(), nullable=False),
            sa.Column("description", sa.TEXT(), nullable=True),
            sa.PrimaryKeyConstraint("id"),
        )

    if "ddsus" not in existing_tables:
        op.create_table(
            "ddsus",
            sa.Column("id", sa.VARCHAR(), nullable=False),
            sa.Column("device_id", sa.INTEGER(), nullable=True),
            sa.Column("voltage", sa.FLOAT(), nullable=True),
            sa.Column("current", sa.FLOAT(), nullable=True),
            sa.Column("power", sa.FLOAT(), nullable=True),
            sa.Column("frequency", sa.FLOAT(), nullable=True),
            sa.Column("power_factor", sa.FLOAT(), nullable=True),
            sa.Column("energy", sa.FLOAT(), nullable=True),
            sa.Column("timestamp", sa.BIGINT(), nullable=True),
            sa.PrimaryKeyConstraint("id"),
        )

    if "pzems" not in existing_tables:
        op.create_table(
            "pzems",
            sa.Column("id", sa.VARCHAR(), nullable=False),
            sa.Column("device_id", sa.INTEGER(), nullable=True),
            sa.Column("voltage", sa.FLOAT(), nullable=True),
            sa.Column("current", sa.FLOAT(), nullable=True),
            sa.Column("power", sa.FLOAT(), nullable=True),
            sa.Column("energy", sa.FLOAT(), nullable=True),
            sa.Column("timestamp", sa.BIGINT(), nullable=True),
            sa.PrimaryKeyConstraint("id"),
        )

    if "shts" not in existing_tables:
        op.create_table(
            "shts",
            sa.Column("id", sa.VARCHAR(), nullable=False),
            sa.Column("device_id", sa.INTEGER(), nullable=True),
            sa.Column("temperature", sa.FLOAT(), nullable=True),
            sa.Column("humidity", sa.FLOAT(), nullable=True),
            sa.Column("timestamp", sa.BIGINT(), nullable=True),
            sa.PrimaryKeyConstraint("id"),
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("shts")
    op.drop_table("pzems")
    op.drop_table("ddsus")
    op.drop_table("devices")
    # ### end Alembic commands ###
